// Translation script - translates all English questions and options to Japanese
const fs = require('fs');
const path = require('path');

const data = JSON.parse(fs.readFileSync(path.join(__dirname, 'src/data/db-exam.json'), 'utf8'));

// Build array from object
const questions = Object.values(data);

// Translation map: English -> Japanese
const qMap = {
  "Which relational algebra operation combines tuples from two relations satisfying a predicate?": "述語を満たす2つのリレーションのタプルを結合する関係代数演算はどれか。",
  "Cartesian product of relations with m and n tuples produces:": "m個とn個のタプルを持つリレーションの直積が生成するタプル数はどれか。",
  "DIVISION operation answers which query type?": "除算演算が応答するクエリの種類はどれか。",
  "FD A->B is trivial if:": "関数従属A→Bが自明なのはどの場合か。",
  "Which NF eliminates transitive dependencies?": "推移的従属を排除する正規形はどれか。",
  "BCNF is stricter than 3NF because it requires:": "BCNFが3NFより厳しい理由は何か。",
  "Which NF addresses multi-valued dependencies?": "多値従属に対処する正規形はどれか。",
  "5NF (Project-Join NF) concerns:": "第5正規形（射影・結合正規形）が対象とするものは何か。",
  "Closure F+ of FDs is:": "関数従属集合Fの閉包F+とは何か。",
  "Armstrong transitivity: A->B, B->C then:": "アームストロングの推移律：A→B、B→C のとき、何が成り立つか。",
  "R(A,B,C) with FDs A->B, B->C violates which NF?": "R(A,B,C)に関数従属A→B, B→Cがある場合、どの正規形に違反するか。",
  "EXISTS in tuple relational calculus is:": "タプル関係計算におけるEXISTSは何を表すか。",
  "A prime attribute is:": "素属性とは何か。",
  "Lossless-join ensures:": "ロスレス結合が保証するものは何か。",
  "Natural join eliminates:": "自然結合が排除するものは何か。",
  "Candidate key is minimal because:": "候補キーが最小である理由は何か。",
  "Outer join includes:": "外部結合に含まれるものは何か。",
  "R(A,B,C,D) with FDs {AB->C,C->D,D->A}: candidate keys?": "R(A,B,C,D)に関数従属{AB→C, C→D, D→A}がある場合、候補キーはいくつか。",
  "Armstrong augmentation: A->B implies:": "アームストロングの拡張律：A→Bが成り立つとき、何が導けるか。",
  "2NF requires:": "第2正規形が要求する条件は何か。",
  "Semi-join returns:": "半結合が返すものは何か。",
  "1NF requires:": "第1正規形が要求する条件は何か。",
  "Attribute closure A+ is:": "属性閉包A+とは何か。",
  "BCNF requires for non-trivial FD X->Y:": "非自明な関数従属X→Yに対するBCNFの要件は何か。",
  "Dependency preservation means:": "従属保存とは何を意味するか。",
  "MVD A->>B means:": "多値従属A→→Bが意味するものは何か。",
  "Correct NF hierarchy:": "正しい正規形の階層はどれか。",
  "Rename operation resolves:": "名前変更演算が解決するものは何か。",
  "Domain calculus {<x,y>|R(x) AND S(y)} produces:": "ドメイン関係計算{<x,y>|R(x) AND S(y)}が生成するものは何か。",
  "Armstrong reflexivity: B subset of A implies:": "アームストロングの反射律：BがAの部分集合のとき、何が成り立つか。",
  "CUBE in GROUP BY generates:": "GROUP BYのCUBEが生成するものは何か。",
  "ROW_NUMBER() vs RANK() difference:": "ROW_NUMBER()とRANK()の違いは何か。",
  "In recursive CTE, anchor and recursive combined by:": "再帰CTEでアンカーと再帰部分を結合する方法はどれか。",
  "LAG() returns:": "LAG()が返すものは何か。",
  "EXISTS returns TRUE when:": "EXISTSがTRUEを返す条件はどれか。",
  "Which set operation removes duplicates?": "重複を削除する集合演算はどれか。",
  "Correlated subquery re-evaluates:": "相関サブクエリが再評価するタイミングはいつか。",
  "(rank-1)/(N-1) is calculated by:": "(rank-1)/(N-1)を計算する関数はどれか。",
  "FILTER clause in aggregates:": "集計関数のFILTER句の役割は何か。",
  "MERGE statement can:": "MERGE文が実行できる操作はどれか。",
  "OVER() clause specifies:": "OVER()句が指定するものは何か。",
  "Which clause filters BEFORE GROUP BY?": "GROUP BYの前にフィルタリングする句はどれか。",
  "Materialized view vs regular view:": "マテリアライズドビューと通常ビューの違いは何か。",
  "ROLLUP produces:": "ROLLUPが生成するものは何か。",
  "NTILE(n) divides rows into:": "NTILE(n)が行をどう分割するか。",
  "Rows in first query NOT in second:": "最初のクエリにあって2番目のクエリにない行を取得する演算はどれか。",
  "LATERAL join allows:": "LATERAL結合が許可するものは何か。",
  "Default frame with ORDER BY:": "ORDER BY指定時のデフォルトフレームはどれか。",
  "Removes all rows, resets identity with minimal logging?": "全行を削除し、IDENTITYをリセットする最小ログ記録の操作はどれか。",
  "WITH CHECK OPTION enforces:": "WITH CHECK OPTIONが施行する制約は何か。",
  "WITH clause (CTE) provides:": "WITH句（CTE）が提供するものは何か。",
  "FIRST_VALUE() returns:": "FIRST_VALUE()が返すものは何か。",
  "Prevents phantoms, allows non-repeatable reads:": "ファントムリードを防ぎ、非リピータブルリードを許容する分離レベルはどれか。",
  "Deterministic SQL function:": "決定的なSQL関数とは何か。",
  "Window frame boundary defined by:": "ウィンドウフレームの境界を定義するものは何か。",
  "GRANT WITH GRANT OPTION allows:": "GRANT WITH GRANT OPTIONが許可するものは何か。",
  "SQL trigger is:": "SQLトリガーとは何か。",
  "= ANY tests:": "= ANYがテストするものは何か。",
  "Recursive CTE must include:": "再帰CTEに必須な要素は何か。",
  "GROUPING SETS allows:": "GROUPING SETSが許可するものは何か。",
  "COALESCE() returns:": "COALESCE()が返すものは何か。",
  "Covering index includes:": "カバリングインデックスに含まれるものは何か。",
  "SELECT FOR UPDATE prevents:": "SELECT FOR UPDATEが防ぐものは何か。",
  "DENSE_RANK vs RANK:": "DENSE_RANKとRANKの違いは何か。",
  "RETURNING clause returns:": "RETURNING句が返すものは何か。",
  "Stored procedure vs function:": "ストアドプロシージャと関数の違いは何か。",
  "SNAPSHOT isolation provides:": "SNAPSHOT分離が提供するものは何か。",
  "FULL OUTER JOIN returns:": "FULL OUTER JOINが返すものは何か。",
  "GROUPING() function used with:": "GROUPING()関数が使用される場面はどこか。",
  "FOREIGN KEY ensures:": "外部キーが保証するものは何か。",
  "Weak entity type:": "弱エンティティ型とは何か。",
  "Ternary relationship involves:": "3項関係が含むものは何か。",
  "Cardinality constraints specify:": "カーディナリティ制約が指定するものは何か。",
  "Denormalization improves:": "非正規化が改善するものは何か。",
  "Identifying relationship:": "識別関係とは何か。",
  "Surrogate key is:": "代理キーとは何か。",
  "Horizontal partitioning splits by:": "水平パーティショニングが分割する基準は何か。",
  "Vertical partitioning advantage:": "垂直パーティショニングの利点は何か。",
  "ER diagram diamond represents:": "ER図のダイヤモンドが表すものは何か。",
  "Supertype/subtype models:": "スーパータイプ/サブタイプがモデル化するものは何か。",
  "Single table inheritance stores:": "単一テーブル継承がデータをどう格納するか。",
  "Recursive relationship connects:": "再帰的関係が接続するものは何か。",
  "Conceptual design produces:": "概念設計が生成するものは何か。",
  "Physical design includes:": "物理設計に含まれるものは何か。",
  "Composite attribute:": "複合属性とは何か。",
  "Range partitioning suits:": "範囲パーティショニングが適している場面はどれか。",
  "Derived attribute:": "導出属性とは何か。",
  "Total participation means:": "全参加とは何を意味するか。",
  "Hash partitioning distributes by:": "ハッシュパーティショニングが分配する基準は何か。",
  "Multivalued attribute requires:": "多値属性が必要とするものは何か。",
  "N:M relationship requires:": "多対多（N:M）関係に必要なものは何か。",
  "Logical design transforms into:": "論理設計が変換先となるものは何か。",
  "Fan-out trap occurs when:": "ファンアウトトラップが発生する条件はどれか。",
  "Pre-aggregation stores:": "事前集計が格納するものは何か。",
  "Choosing primary keys: which phase?": "主キーの選択はどの設計フェーズで行うか。",
  "List partitioning assigns by:": "リストパーティショニングが割り当てる基準は何か。",
  "Chasm trap:": "カズムトラップとは何か。",
  "Data dictionary stores:": "データディクショナリが格納するものは何か。",
  "Temporal data uses:": "履歴データが使用する手法は何か。",
  "Bridge table resolves:": "ブリッジテーブルが解決するものは何か。",
  "ACID Atomicity ensures:": "ACIDの原子性が保証するものは何か。",
  "Dirty read occurs when:": "ダーティリードが発生する条件はどれか。",
  "Prevents dirty reads, allows non-repeatable:": "ダーティリードを防ぎ、非リピータブルリードを許容する分離レベルはどれか。",
  "Deadlock occurs when:": "デッドロックが発生する条件はどれか。",
  "MVCC improves concurrency by:": "MVCCが並行性を改善する仕組みは何か。",
  "Phantom read:": "ファントムリードとは何か。",
  "WAL requires:": "WAL（先行書き込みログ）が要求するものは何か。",
  "Shared lock allows:": "共有ロックが許可するものは何か。",
  "Two-phase locking ensures:": "2相ロックが保証するものは何か。",
  "Non-repeatable read:": "非リピータブルリードとは何か。",
  "Wait-die scheme:": "Wait-die方式の説明で正しいものはどれか。",
  "SERIALIZABLE prevents:": "SERIALIZABLEが防ぐものはどれか。",
  "Intent lock signals:": "インテントロックが示すものは何か。",
  "Optimistic concurrency assumes:": "楽観的並行性制御の前提は何か。",
  "SAVEPOINT allows:": "SAVEPOINTが許可する操作は何か。",
  "Strict 2PL requires:": "厳密2相ロックが要求する条件は何か。",
  "Cascading rollback:": "カスケードロールバックとは何か。",
  "Checkpoint reduces:": "チェックポイントが削減するものは何か。",
  "Wound-wait scheme:": "Wound-wait方式の説明で正しいものはどれか。",
  "Undo/redo recovery uses:": "Undo/Redoリカバリが使用するものは何か。",
  "Non-repeatable vs phantom:": "非リピータブルリードとファントムリードの違いは何か。",
  "ARIES algorithm uses:": "ARIESアルゴリズムが使用する方式はどれか。",
  "Update lock prevents:": "更新ロックが防ぐものは何か。",
  "ACID Durability ensures:": "ACIDの永続性が保証するものは何か。",
  "Snapshot isolation allows:": "SNAPSHOT分離が許可・防止するものは何か。",
  "Query plan generated by:": "クエリ実行計画を生成するものは何か。",
  "Cost-based optimization uses:": "コストベース最適化が使用するものは何か。",
  "Hash join best when:": "ハッシュ結合が最適な条件はどれか。",
  "Nested-loop join complexity:": "ネステッドループ結合の計算量はどれか。",
  "Merge join requires:": "マージ結合が要求する条件は何か。",
  "Predicate pushdown:": "述語プッシュダウンとは何か。",
  "Most important optimizer stats:": "オプティマイザ統計で最も重要なものは何か。",
  "Index scan preferred when:": "インデックススキャンが推奨される条件はどれか。",
  "Covering index eliminates:": "カバリングインデックスが排除するものは何か。",
  "Which join produces sorted output?": "ソート済み出力を生成する結合方式はどれか。",
  "Selectivity = ": "選択性とは何か。",
  "Left-deep tree:": "左深さツリーとは何か。",
  "Histograms estimate:": "ヒストグラムが推定するものは何か。",
  "Subquery unnesting:": "サブクエリのネスト解除とは何か。",
  "Full scan preferred when:": "フルスキャンが推奨される条件はどれか。",
  "EXPLAIN shows:": "EXPLAINが表示するものは何か。",
  "Parallel query divides by:": "並列クエリが分割する基準は何か。",
  "Selinger optimizer uses:": "セリンジャーオプティマイザが使用する手法は何か。",
  "Bitmap index best for:": "ビットマップインデックスが最適な場面はどれか。",
  "View merging:": "ビューマージとは何か。",
  "Bloom filter in hash join:": "ハッシュ結合におけるブルームフィルタの役割は何か。",
  "Index-only scan requires:": "インデックスオンリースキャンが要求する条件は何か。",
  "Rule-based uses:": "ルールベース最適化が使用するものは何か。",
  "Cardinality estimator predicts:": "カーディナリティ推定器が予測するものは何か。",
  "OR expansion transforms to:": "OR展開が変換先となるものは何か。",
  "B-tree O(log N) for:": "B-treeがO(log N)で実行できる操作はどれか。",
  "B+tree main feature:": "B+treeの主な特徴は何か。",
  "Fill factor determines:": "フィルファクタが決定するものは何か。",
  "Composite (A,B,C) searches on:": "複合インデックス(A,B,C)で検索可能な組み合わせはどれか。",
  "Hash index best for:": "ハッシュインデックスが最適な場面はどれか。",
  "Clustered index determines:": "クラスタ化インデックスが決定するものは何か。",
  "Bitmap index uses:": "ビットマップインデックスが使用する仕組みは何か。",
  "Index rebuild:": "インデックス再構築の目的は何か。",
  "Left-prefix for (city,last_name,first_name):": "(city,last_name,first_name)の左端プレフィクスとして有効な組み合わせはどれか。",
  "Non-clustered stores:": "非クラスタ化インデックスが格納するものは何か。",
  "Index selectivity = ": "インデックス選択性とは何か。",
  "Auto-maintained indexes:": "自動保守されるインデックスはどれか。",
  "Functional index indexes:": "関数インデックスがインデックス化するものは何か。",
  "Fragmentation caused by:": "フラグメンテーションの原因は何か。",
  "Partial index includes:": "部分インデックスに含まれる行はどれか。",
  "Best for ORDER BY LIMIT:": "ORDER BY LIMITに最適なインデックスはどれか。",
  "Covering index avoids:": "カバリングインデックスが回避するものは何か。",
  "Too many indexes degrade:": "インデックスが多すぎると劣化するものは何か。",
  "GiST is:": "GiSTとは何か。",
  "B+tree logarithmic depth due to:": "B+treeが対数の深さになる理由は何か。",
  "CAP theorem: at most:": "CAP定理：同時に満たせるのは最大いくつか。",
  "Two-phase commit phases:": "2相コミットのフェーズはどれか。",
  "Eventual consistency:": "結果整合性とは何か。",
  "Sharding distributes:": "シャーディングが分散するものは何か。",
  "Synchronous replication acknowledges:": "同期レプリケーションが確認するものは何か。",
  "Split-brain:": "スプリットブレインとは何か。",
  "Quorum requires:": "クオラムが要求するものは何か。",
  "Paxos/Raft ensure:": "Paxos/Raftが保証するものは何か。",
  "Strongest consistency:": "最も強い整合性モデルはどれか。",
  "Distributed deadlock involves:": "分散デッドロックの特徴は何か。",
  "Async replication primary acks:": "非同期レプリケーションでプライマリが応答するタイミングはいつか。",
  "Consistent hashing advantage:": "コンシステントハッシュの利点は何か。",
  "Vector clocks track:": "ベクトルクロックが追跡するものは何か。",
  "Distributed tx needs:": "分散トランザクションに必要なプロトコルは何か。",
  "Read-your-writes:": "読み取り自身書き込みとは何か。",
  "Multi-master allows:": "マルチマスタが許可するものは何か。",
  "W+R>N ensures:": "W+R>Nが保証するものは何か。",
  "Distributed query handles:": "分散クエリが処理する方式はどれか。",
  "Vertical fragmentation:": "垂直フラグメンテーションが分散するものは何か。",
  "Three-phase commit adds:": "3相コミットが追加するものは何か。",
  "Document store best for:": "ドキュメントストアが最適なデータはどれか。",
  "BASE stands for:": "BASEの意味はどれか。",
  "Key-value optimized for:": "キーバリューストアが最適化されている操作はどれか。",
  "Graph DBs excel at:": "グラフDBが得意な処理は何か。",
  "Column-family optimized for:": "カラムファミリが最適化されている場面はどれか。",
  "NewSQL provides:": "NewSQLが提供するものは何か。",
  "Many NoSQL favor CAP:": "多くのNoSQLがCAPで優先するものはどれか。",
  "Polyglot persistence:": "ポリグロット永続性とは何か。",
  "Cassandra tunes consistency via:": "Cassandraが整合性を調整する仕組みは何か。",
  "Causal consistency ensures:": "因果整合性が保証するものは何か。",
  "NewSQL uses:": "NewSQLが使用する技術は何か。",
  "Time-series DB optimized for:": "時系列DBが最適化されているデータはどれか。",
  "NoSQL disadvantage:": "NoSQLの欠点はどれか。",
  "MapReduce:": "MapReduceとは何か。",
  "Column-family stores by:": "カラムファミリがデータを格納する方式は何か。",
  "Data classification by:": "データ分類の基準は何か。",
  "Encryption at rest protects:": "保管時暗号化が保護するものは何か。",
  "GDPR data minimization:": "GDPRデータ最小化の原則とは何か。",
  "Row-Level Security:": "行レベルセキュリティとは何か。",
  "Audit trail records:": "監査証跡が記録するものは何か。",
  "TLS/SSL protects:": "TLS/SSLが保護するものは何か。",
  "GDPR right to erasure:": "GDPR忘れられる権利とは何か。",
  "Dynamic data masking:": "動的データマスキングとは何か。",
  "RBAC assigns to:": "RBACが権限を割り当てる対象は何か。",
  "Data retention defines:": "データ保持ポリシーが定義するものは何か。",
  "SQL injection prevention:": "SQLインジェクション対策として有効なものはどれか。",
  "Tokenization replaces with:": "トークン化が置き換えるものは何か。",
  "Least privilege:": "最小権限の原則とは何か。",
  "Non-production masking:": "非本番環境マスキングとは何か。",
  "TDE encrypts:": "TDEが暗号化するものは何か。",
  "Full backup copies:": "フルバックアップがコピーするものは何か。",
  "Incremental copies:": "増分バックアップがコピーするものは何か。",
  "Differential copies:": "差分バックアップがコピーするものは何か。",
  "RPO defines:": "RPOが定義するものは何か。",
  "RTO defines:": "RTOが定義するものは何か。",
  "Point-in-time recovery uses:": "ポイントインタイムリカバリが使用するものは何か。",
  "Hot backup:": "ホットバックアップとは何か。",
  "Cold backup:": "コールドバックアップとは何か。",
  "Transaction log backups enable:": "トランザクションログバックアップが可能にするものは何か。",
  "Restore order (full+diff+logs):": "リストア順序（フル+差分+ログ）として正しいものはどれか。",
  "Snapshot backup uses:": "スナップショットバックアップが使用する技術は何か。",
  "Checksum verification ensures:": "チェックサム検証が保証するものは何か。",
  "3-2-1 rule:": "バックアップの3-2-1ルールとは何か。",
  "Log shipping:": "ログシッピングとは何か。",
  "SIMPLE recovery model:": "SIMPLE復旧モデルの特徴はどれか。",
  "Standby in HA:": "高可用性スタンバイの説明で正しいものはどれか。",
  "Backup verification:": "バックアップ検証とは何か。",
  "WAL recovery:": "WALリカバリの方式はどれか。",
  "RPO 15 min = max backup interval:": "RPO15分の場合の最大バックアップ間隔はどれか。",
  "Corrupted unrestoreable backup:": "破損したリストア不可バックアップが示す教訓は何か。",
  "Best RTO minimization:": "RTO最小化に最適な方法はどれか。",
  "Recovery plan includes:": "リカバリ計画に含まれるべきものは何か。",
  "GFS rotation manages:": "世代ファイル管理（GFS）が管理するものは何か。",
  "Crash recovery after power failure:": "停電後のクラッシュリカバリ方法はどれか。",
  "Online vs archived redo log:": "オンラインREDOログとアーカイブREDOログの違いは何か。",
  "Incremental vs differential restore:": "増分リストアと差分リストアの違いは何か。",
  "Database mirroring:": "データベースミラーリングとは何か。",
  "GFS scheme manages:": "GFS方式が管理するものは何か。",
  "Recover from accidental DROP TABLE:": "誤ったDROP TABLEからのリカバリ方法はどれか。",
  "Backup window is:": "バックアップウィンドウとは何か。"
};

// Options translation map
const oMap = {
  "Selection": "選択",
  "Projection": "射影",
  "Join": "結合",
  "Division": "除算",
  "m+n tuples": "m+n個のタプル",
  "m*n tuples": "m×n個のタプル",
  "max(m,n)": "max(m,n)",
  "min(m,n)": "min(m,n)",
  "OR conditions": "OR条件",
  "EXISTS queries": "EXISTSクエリ",
  "For-all queries": "全称クエリ（∀）",
  "Aggregations": "集計",
  "A is a candidate key": "Aが候補キー",
  "B is subset of A": "BがAの部分集合",
  "A is subset of B": "AがBの部分集合",
  "A and B disjoint": "AとBが互いに素",
  "1NF": "第1正規形",
  "2NF": "第2正規形",
  "3NF": "第3正規形",
  "BCNF": "ボイス・コッド正規形（BCNF）",
  "All attrs must be prime": "すべての属性が素属性",
  "Every determinant to be a superkey": "すべての決定項がスーパーキー",
  "No MVDs allowed": "多値従属は許可されない",
  "Single-valued only": "単一値のみ",
  "4NF": "第4正規形",
  "5NF": "第5正規形",
  "MVDs": "多値従属",
  "FDs": "関数従属",
  "Join dependencies": "結合従属",
  "Transitive deps": "推移的従属",
  "Minimal set equivalent to F": "Fと等価な最小集合",
  "All FDs derivable via Armstrong axioms": "アームストロング公理から導出可能なすべての関数従属",
  "FDs in current DB state": "現在のDB状態の関数従属",
  "Subset of F in BCNF": "BCNFでのFの部分集合",
  "A->C": "A→C",
  "C->A": "C→A",
  "A->B and A->C": "A→B かつ A→C",
  "B->A and C->B": "B→A かつ C→B",
  "1NF only": "第1正規形のみ",
  "2NF": "第2正規形",
  "3NF": "第3正規形",
  "BCNF": "ボイス・コッド正規形",
  "Universal quantification": "全称量化",
  "Existential quantification": "存在量化",
  "Negation": "否定",
  "Part of any candidate key": "いずれかの候補キーの一部",
  "First attr of primary key": "主キーの先頭属性",
  "Always unique": "常に一意",
  "Cannot be NULL": "NULL不可",
  "Dependency preservation": "従属保存",
  "Original recoverable by join": "結合で元のリレーションが復元可能",
  "Minimal redundancy": "最小の冗長性",
  "Attribute preservation": "属性保存",
  "Left duplicates": "左側の重複",
  "Duplicate join column": "重複する結合列",
  "All NULLs": "すべてのNULL",
  "Non-matching tuples": "一致しないタプル",
  "Fewest attributes": "最も少ない属性",
  "No proper subset is superkey": "真部分集合がスーパーキーにならない",
  "Only non-nulls": "非NULLのみ",
  "Chosen primary key": "選ばれた主キー",
  "Nothing extra": "追加なし",
  "Unmatched tuples with NULLs": "一致しないタプルをNULL付きで含む",
  "No duplicates": "重複なし",
  "Sorted results": "ソート済み結果",
  "Armstrong augmentation: A->B implies:": "アームストロングの拡張律：A→Bが成り立つとき、何が導けるか。",
  "Atomic values": "原子値",
  "No partial dependency on candidate keys": "候補キーへの部分従属がない",
  "No transitive deps": "推移的従属がない",
  "Every determinant superkey": "すべての決定項がスーパーキー",
  "All R tuples": "Rのすべてのタプル",
  "R tuples matching S": "Sに一致するRのタプル",
  "S tuples matching R": "Rに一致するSのタプル",
  "R intersect S": "RとSの共通部分",
  "Unique values": "一意な値",
  "Atomic values": "原子値",
  "Dependence on entire key": "キー全体への従属",
  "Primary key": "主キー",
  "All attrs dependent on A": "Aに従属するすべての属性",
  "All FDs A determines": "Aが決定するすべての関数従属",
  "Superkey containing A": "Aを含むスーパーキー",
  "Candidate keys with A": "Aを含む候補キー",
  "Y is prime": "Yが素属性",
  "X is superkey": "Xがスーパーキー",
  "Y not subset X": "YがXの部分集合でない",
  "X is candidate key": "Xが候補キー",
  "All FDs checkable on decomposed relations": "すべての関数従属が分解後のリレーションで検査可能",
  "All data preserved": "すべてのデータが保存される",
  "No redundancy": "冗長性なし",
  "Faster queries": "クエリが高速",
  "B functionally determined by A": "BがAに関数従属",
  "B values independent of C per A": "AごとにBの値がCから独立",
  "A determines B and C": "AがBとCを決定",
  "B,C same cardinality per A": "AごとにB,Cのカーディナリティが同じ",
  "BCNF=>4NF=>3NF": "BCNF⇒4NF⇒3NF",
  "5NF=>4NF=>BCNF=>3NF": "5NF⇒4NF⇒BCNF⇒3NF",
  "3NF=>BCNF=>4NF": "3NF⇒BCNF⇒4NF",
  "4NF=>5NF=>BCNF": "4NF⇒5NF⇒BCNF",
  "Performance issues": "パフォーマンス問題",
  "Naming conflicts": "命名衝突",
  "Sorting problems": "ソート問題",
  "Duplicate rows": "重複行",
  "Intersection": "積（共通部分）",
  "Cartesian product": "直積",
  "Natural join": "自然結合",
  "Union": "和（UNION）",
  "A->B": "A→B",
  "B->A": "B→A",
  "A+B->A": "A+B→A",
  "A->A union B": "A→A∪B",
  "All column combinations": "すべての列の組み合わせ",
  "Hierarchical subtotals": "階層的小計",
  "Grand total only": "総計のみ",
  "Specified levels": "指定されたレベル",
  "Identical": "同じ",
  "RANK gives ties same rank and skips numbers": "RANKは同順に同じ順位を付け、次の順位を飛ばす",
  "ROW_NUMBER not window function": "ROW_NUMBERはウィンドウ関数でない",
  "RANK cannot ORDER BY": "RANKはORDER BY不可",
  "UNION": "UNION",
  "UNION ALL": "UNION ALL",
  "JOIN": "JOIN",
  "INTERSECT": "INTERSECT",
  "Next row value": "次の行の値",
  "Previous row value": "前の行の値",
  "Difference from previous": "前の行との差分",
  "Current row position": "現在の行の位置",
  "Subquery returns count": "サブクエリが件数を返す",
  "Subquery returns at least one row": "サブクエリが1行以上返す",
  "All rows match": "すべての行が一致",
  "Column exists": "列が存在する",
  "UNION ALL": "UNION ALL",
  "INTERSECT ALL": "INTERSECT ALL",
  "UNION": "UNION",
  "EXCEPT ALL": "EXCEPT ALL",
  "Once only": "1回のみ",
  "For each outer query row": "外部クエリの各行ごと",
  "After outer completes": "外部クエリ完了後",
  "When optimizer decides": "オプティマイザが決定したとき",
  "ROW_NUMBER": "ROW_NUMBER",
  "RANK": "RANK",
  "PERCENT_RANK": "PERCENT_RANK",
  "CUME_DIST": "CUME_DIST",
  "Sorts input": "入力をソート",
  "Conditionally includes rows": "条件付きで行を含める",
  "Filters final result": "最終結果をフィルタ",
  "Removes NULLs": "NULLを削除",
  "Only INSERT": "INSERTのみ",
  "Only UPDATE": "UPDATEのみ",
  "INSERT, UPDATE, DELETE based on match": "一致に応じてINSERT、UPDATE、DELETE",
  "SELECT and INSERT only": "SELECTとINSERTのみ",
  "Table to query": "クエリ対象テーブル",
  "Partitioning and ordering for window": "ウィンドウのパーティショニングと順序付け",
  "Filter condition": "フィルタ条件",
  "Join condition": "結合条件",
  "HAVING": "HAVING",
  "WHERE": "WHERE",
  "QUALIFY": "QUALIFY",
  "FILTER": "FILTER",
  "Cannot be queried": "クエリ不可",
  "Result stored on disk": "結果をディスクに格納",
  "No joins supported": "結合非対応",
  "Always current": "常に最新",
  "All combinations": "すべての組み合わせ",
  "Hierarchical subtotals and grand total": "階層的小計と総計",
  "Grand total only": "総計のみ",
  "Cross-tabulation": "クロス集計",
  "n equal parts": "n個の等分グループ",
  "n columns": "n列",
  "n subqueries": "n個のサブクエリ",
  "n tables": "n個のテーブル",
  "INTERSECT": "INTERSECT",
  "UNION": "UNION",
  "EXCEPT (MINUS)": "EXCEPT（MINUS）",
  "DIFFERENCE": "DIFFERENCE",
  "Cross-DB queries": "クロスDBクエリ",
  "Subquery to reference preceding FROM columns": "サブクエリが前方のFROM列を参照可能",
  "Recursive queries": "再帰クエリ",
  "Parallel execution": "並列実行",
  "ROWS UNBOUNDED to CURRENT ROW": "ROWS UNBOUNDED TO CURRENT ROW",
  "RANGE UNBOUNDED to CURRENT ROW": "RANGE UNBOUNDED TO CURRENT ROW",
  "ROWS UNBOUNDED both": "ROWS UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING",
  "RANGE UNBOUNDED both": "RANGE UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING",
  "DELETE FROM": "DELETE FROM",
  "DROP TABLE": "DROP TABLE",
  "TRUNCATE TABLE": "TRUNCATE TABLE",
  "REMOVE TABLE": "REMOVE TABLE",
  "Performance": "パフォーマンス",
  "Inserts/updates satisfy view WHERE clause": "INSERT/UPDATEがビューのWHERE句を満たす",
  "View updatable": "ビューが更新可能",
  "Referential integrity": "参照整合性",
  "Transaction boundary": "トランザクション境界",
  "Named temporary result set": "名前付き一時結果セット",
  "Security context": "セキュリティコンテキスト",
  "Connection pooling": "コネクションプーリング",
  "First column": "最初の列",
  "Value from first row of window frame": "ウィンドウフレームの最初の行の値",
  "First row number": "最初の行番号",
  "Minimum value": "最小値",
  "READ UNCOMMITTED": "READ UNCOMMITTED",
  "READ COMMITTED": "READ COMMITTED",
  "REPEATABLE READ": "REPEATABLE READ",
  "SERIALIZABLE": "SERIALIZABLE",
  "Always returns NULL": "常にNULLを返す",
  "Same result for same input": "同じ入力には常に同じ結果",
  "Modifies data": "データを変更",
  "Used in triggers": "トリガーで使用",
  "PARTITION BY": "PARTITION BY",
  "ORDER BY": "ORDER BY",
  "ROWS/RANGE BETWEEN...AND...": "ROWS/RANGE BETWEEN...AND...",
  "GROUP BY": "GROUP BY",
  "Creating tables": "テーブル作成",
  "Grantee to grant privileges to others": "被権限者が他者に権限を付与可能",
  "Revoking privileges": "権限取消",
  "System access": "システムアクセス",
  "Manual stored procedure": "手動ストアドプロシージャ",
  "Auto-executed on table event": "テーブルイベントで自動実行",
  "Constraint": "制約",
  "Index type": "インデックスタイプ",
  "No values": "値なし",
  "Any value in subquery result": "サブクエリ結果のいずれかの値",
  "All values": "すべての値",
  "First value": "最初の値",
  "Two anchors": "2つのアンカー",
  "UNION ALL between anchor and recursive": "アンカーと再帰部をUNION ALLで結合",
  "LIMIT": "LIMIT",
  "ORDER BY": "ORDER BY",
  "All CUBE combos": "すべてのCUBE組み合わせ",
  "Multiple GROUP BY groupings in one query": "1クエリで複数のGROUP BYグループ化",
  "Creating grouping columns": "グループ化列の作成",
  "Rollup hierarchies": "ロールアップ階層",
  "First non-NULL argument": "最初の非NULL引数",
  "Last non-NULL": "最後の非NULL",
  "NULL if any NULL": "いずれかがNULLならNULL",
  "Average of non-NULLs": "非NULLの平均",
  "Only primary key": "主キーのみ",
  "All columns needed by query": "クエリが必要とするすべての列",
  "All table columns": "テーブルのすべての列",
  "Only foreign keys": "外部キーのみ",
  "Reads": "読み取り",
  "Concurrent modification of selected rows": "選択行の同時変更",
  "All queries": "すべてのクエリ",
  "FK checks": "外部キーチェック",
  "Different sorting": "異なるソート",
  "DENSE_RANK does not skip ranks after ties": "DENSE_RANKは同順後に順位を飛ばさない",
  "Numeric only": "数値のみ",
  "Requires partition": "パーティション必須",
  "Affected row count": "影響を受けた行数",
  "The modified data": "変更されたデータ",
  "Status code": "ステータスコード",
  "Transaction ID": "トランザクションID",
  "Must return value": "戻り値必須",
  "Cannot contain SQL": "SQLを含められない",
  "Can return multiple result sets": "複数の結果セットを返せる",
  "No parameters": "パラメータなし",
  "Blocked reads": "読み取りのブロック",
  "Consistent view from transaction start": "トランザクション開始時の整合性のあるビュー",
  "Dirty reads": "ダーティリード",
  "Phantom reads": "ファントムリード",
  "Only matching rows": "一致する行のみ",
  "All left rows": "左のすべての行",
  "All rows from both with NULLs": "両方のすべての行（一致しない場合はNULL）",
  "All right rows": "右のすべての行",
  "Regular GROUP BY": "通常のGROUP BY",
  "CUBE/ROLLUP/GROUPING SETS": "CUBE/ROLLUP/GROUPING SETS",
  "Window functions": "ウィンドウ関数",
  "Subqueries": "サブクエリ",
  "Uniqueness": "一意性",
  "Referential integrity": "参照整合性",
  "Non-null": "非NULL",
  "Default values": "デフォルト値",
  "Has no attributes": "属性を持たない",
  "Depends on strong entity for identification": "識別に強エンティティに依存",
  "Has composite key": "複合キーを持つ",
  "Is optional": "省略可能",
  "Three attributes": "3つの属性",
  "Three entity types": "3つのエンティティ型",
  "Three weak entities": "3つの弱エンティティ",
  "Three primary keys": "3つの主キー",
  "Max attribute count": "最大属性数",
  "Entity participation count in relationships": "関係におけるエンティティ参加数",
  "Database size": "データベースサイズ",
  "Table count": "テーブル数",
  "NF compliance": "正規形準拠",
  "Read performance at cost of redundancy": "冗長性を犠牲に読み取り性能を向上",
  "Storage efficiency": "ストレージ効率",
  "Dependency elimination": "従属の排除",
  "Both weak entities": "両方が弱エンティティ",
  "Weak entity key includes strong entity key": "弱エンティティキーが強エンティティキーを含む",
  "Only foreign keys": "外部キーのみ",
  "Surrogate key": "代理キー",
  "Foreign key": "外部キー",
  "Artificially generated unique identifier": "人工的に生成された一意識別子",
  "Composite PK": "複合主キー",
  "Secondary index": "セカンダリインデックス",
  "Columns": "列",
  "Rows based on partition key": "パーティションキーに基づく行",
  "Tables": "テーブル",
  "Data types": "データ型",
  "Easier joins": "結合が容易",
  "Faster full scans": "フルスキャンが高速",
  "Reduced I/O accessing only needed columns": "必要な列のみアクセスしI/O削減",
  "Simplified schema": "スキーマが簡素化",
  "Entity": "エンティティ",
  "Attribute": "属性",
  "Relationship": "リレーションシップ",
  "Primary key": "主キー",
  "One-to-many": "1対多",
  "Specialization/generalization hierarchies": "特化/汎化階層",
  "Self-referencing": "自己参照",
  "Cross-table joins": "テーブル間結合",
  "Separate tables": "別々のテーブル",
  "All types in one table with discriminator": "すべてのタイプを1テーブルに識別子付きで格納",
  "No subtypes": "サブタイプなし",
  "Only common attrs": "共通属性のみ",
  "Two entities": "2つのエンティティ",
  "Entity to itself": "エンティティ自身への接続",
  "Three entities": "3つのエンティティ",
  "Weak to strong": "弱から強",
  "SQL statements": "SQL文",
  "DBMS-independent ER model": "DBMSに依存しないERモデル",
  "Physical specs": "物理仕様",
  "Index definitions": "インデックス定義",
  "Entity definitions": "エンティティ定義",
  "Data types, indexes, storage": "データ型、インデックス、ストレージ",
  "Normalization": "正規化",
  "ER diagrams": "ER図",
  "Multiple values": "複数の値",
  "Composed of sub-attributes": "下位属性で構成",
  "Foreign key": "外部キー",
  "Derived attr": "導出属性",
  "Uniform distribution": "均一分布",
  "Range-based query filters": "範囲ベースのクエリフィルタ",
  "Equality conditions": "等価条件",
  "Small tables": "小さいテーブル",
  "From another table": "別テーブルからの値",
  "Computed from other attrs": "他の属性から計算",
  "PK component": "主キーの構成要素",
  "Always unique": "常に一意",
  "Every entity must participate": "すべてのエンティティが必ず参加",
  "Max one per relationship": "関係につき最大1つ",
  "Optional": "任意",
  "Unlimited": "無制限",
  "Ranges": "範囲",
  "Hash function on partition key": "パーティションキーでのハッシュ関数",
  "Manual": "手動",
  "Date": "日付",
  "Composite key": "複合キー",
  "Separate table": "別テーブル",
  "CHECK constraint": "CHECK制約",
  "DEFAULT": "DEFAULT",
  "Foreign key": "外部キー",
  "Associative entity (junction table)": "結合エンティティ（中間テーブル）",
  "UNIQUE constraint": "UNIQUE制約",
  "Composite attr": "複合属性",
  "Physical layout": "物理レイアウト",
  "Relational schema": "リレーショナルスキーマ",
  "Application code": "アプリケーションコード",
  "Network protocol": "ネットワークプロトコル",
  "Too many joins": "結合が多すぎる",
  "Paths between entities lose information": "エンティティ間の経路で情報が欠落",
  "Too many FKs": "外部キーが多すぎる",
  "Index too large": "インデックスが大きすぎる",
  "Merged tables": "マージされたテーブル",
  "Pre-computed aggregations": "事前計算済み集計値",
  "Duplicate columns": "重複列",
  "Reference tables": "参照テーブル",
  "Requirements": "要件定義",
  "Conceptual": "概念設計",
  "Logical": "論理設計",
  "Physical": "物理設計",
  "Hash": "ハッシュ",
  "Explicit value list": "明示的な値リスト",
  "Ranges": "範囲",
  "Random": "ランダム",
  "Too many NULLs": "NULLが多すぎる",
  "Optional relationships hide missing paths": "オプション関係が欠落経路を隠す",
  "Duplicate rows": "重複行",
  "Missing FKs": "外部キーの欠落",
  "Encrypted data": "暗号化データ",
  "Metadata about DB structure": "DB構造のメタデータ",
  "Backup data": "バックアップデータ",
  "Optimization": "最適化",
  "Timestamp only": "タイムスタンプのみ",
  "SCD patterns": "SCDパターン",
  "5NF": "第5正規形",
  "Denormalization": "非正規化",
  "Facts": "ファクト",
  "M:N between facts and dimensions": "ファクトとディメンションの多対多",
  "Indexes": "インデックス",
  "Partitions": "パーティション",
  "Simultaneous transactions": "同時トランザクション",
  "All-or-nothing transactions": "全か無かのトランザクション",
  "Consistency": "一貫性",
  "Isolation": "独立性",
  "Reading own uncommitted": "自身の未コミットデータを読み取り",
  "Reading uncommitted from another tx": "他のトランザクションの未コミットデータを読み取り",
  "Reading deleted data": "削除されたデータを読み取り",
  "Reading corrupted blocks": "破損ブロックを読み取り",
  "READ UNCOMMITTED": "READ UNCOMMITTED",
  "READ COMMITTED": "READ COMMITTED",
  "REPEATABLE READ": "REPEATABLE READ",
  "SERIALIZABLE": "SERIALIZABLE",
  "Tx runs forever": "トランザクションが永遠に実行",
  "Txs wait for each other's locks": "トランザクションが互いのロックを待機",
  "Log full": "ログが一杯",
  "Tx aborted": "トランザクションが中断",
  "Locking all rows": "すべての行をロック",
  "Multiple row versions": "複数の行バージョン",
  "Serializing txs": "トランザクションを直列化",
  "Preventing concurrent access": "同時アクセスを防止",
  "Read row disappears": "読み取った行が消える",
  "Re-executed query sees new committed rows": "再実行で新しくコミットされた行が見える",
  "Data duplicated": "データが重複",
  "Unexpected NULL": "予期しないNULL",
  "Data before log": "ログ前のデータ",
  "Log to stable storage before DB modification": "DB変更前にログを安定ストレージに書き込み",
  "Logging all queries": "すべてのクエリをログ記録",
  "Remote logs": "リモートログ",
  "No concurrent access": "同時アクセス不可",
  "Multiple readers no writers": "複数リーダー、ライターなし",
  "Only one reader": "リーダー1人のみ",
  "Lock holder only": "ロック保持者のみ",
  "Two-step completion": "2ステップ完了",
  "Conflict serializability": "競合直列化可能性",
  "No deadlocks": "デッドロックなし",
  "Maximum parallelism": "最大並行性",
  "Different row count": "行数が異なる",
  "Same row different values on re-read": "再読み取りで同じ行の値が異なる",
  "Query fails": "クエリ失敗",
  "Wrong table": "間違ったテーブル",
  "Aborts older": "古いトランザクションを中止",
  "Older wait, younger die": "古いものは待機、新しいものは中止",
  "Optimistic": "楽観的",
  "Timeout": "タイムアウト",
  "Dirty reads": "ダーティリード",
  "Dirty + non-repeatable": "ダーティリード＋非リピータブルリード",
  "All three: dirty + non-repeatable + phantom": "ダーティリード＋非リピータブルリード＋ファントムリードのすべて",
  "All including deadlocks": "すべて＋デッドロック",
  "Commit intention": "コミット意図",
  "Intention to lock lower-level items": "下位レベル項目のロック意図",
  "DB-level lock": "DBレベルロック",
  "Row shared lock": "行共有ロック",
  "Conflicts always": "衝突は常にある",
  "Conflicts rare, validate at commit": "衝突はまれ、コミット時に検証",
  "No concurrent access": "同時アクセスなし",
  "Read-only": "読み取り専用",
  "New tx": "新しいトランザクション",
  "Rollback to point within tx": "トランザクション内のポイントへロールバック",
  "Permanent save": "永続保存",
  "Partial commit": "部分コミット",
  "All locks simultaneous": "すべてのロックを同時取得",
  "Exclusive locks held until commit/abort": "排他ロックをコミット/中止まで保持",
  "Only shared locks": "共有ロックのみ",
  "Per-statement release": "ステートメントごとに解放",
  "Single rollback": "単一ロールバック",
  "Aborting one forces dependent txs to rollback": "1つの中止が依存トランザクションを連鎖ロールバック",
  "DB restore": "DBリストア",
  "Deadlock resolution": "デッドロック解決",
  "Backup size": "バックアップサイズ",
  "Recovery time": "リカバリ時間",
  "Deadlocks": "デッドロック",
  "Query time": "クエリ時間",
  "Older preempts younger": "古いものが若いものを先制",
  "Waits for all": "すべてを待機",
  "Timeout": "タイムアウト",
  "Undo only": "UNDOのみ",
  "Both before-image and after-image": "変更前イメージと変更後イメージの両方",
  "Physical logging": "物理ログ",
  "Checkpoint only": "チェックポイントのみ",
  "Same thing": "同じ",
  "Non-repeatable: existing row changes; phantom: new rows": "非リピータブルは既存行の変更、ファントムは新規行の出現",
  "Phantoms need indexes": "ファントムにはインデックスが必要",
  "Non-repeatable more serious": "非リピータブルの方が深刻",
  "Undo only": "UNDOのみ",
  "Redo only": "REDOのみ",
  "Three passes: analysis, redo, undo": "3パス：分析、REDO、UNDO",
  "Shadow paging": "シャドウページング",
  "Row locking": "行ロック",
  "Conversion deadlock S<->X": "S→X変換デッドロック",
  "Table locking": "テーブルロック",
  "Index locking": "インデックスロック",
  "Atomicity": "原子性",
  "Consistency": "一貫性",
  "Isolation": "独立性",
  "Changes survive failures": "変更が障害後も維持される",
  "All anomalies": "すべての異常",
  "Dirty/non-repeatable/phantom prevented, write skew possible": "ダーティ/非リピータブル/ファントム防止、書き込みスキュー可能",
  "Only dirty reads": "ダーティリードのみ",
  "All including deadlocks": "すべて＋デッドロック",
  "Storage engine": "ストレージエンジン",
  "Query optimizer": "クエリオプティマイザ",
  "Tx manager": "トランザクションマネージャ",
  "Log manager": "ログマネージャ",
  "SQL syntax": "SQL構文",
  "I/O, CPU, memory costs": "I/O、CPU、メモリコスト",
  "Table names": "テーブル名",
  "Column count": "列数",
  "Both small": "両方が小さい",
  "Smaller input fits in memory": "小さい方の入力がメモリに収まる",
  "Both sorted": "両方がソート済み",
  "One indexed": "一方がインデックス付き",
  "O(N+M)": "O(N+M)",
  "O(N*M)": "O(N×M)",
  "O(N log N)": "O(N log N)",
  "O(N+M log M)": "O(N+M log M)",
  "No prerequisites": "前提条件なし",
  "Both inputs sorted on join key": "両方の入力が結合キーでソート済み",
  "Hash table": "ハッシュテーブル",
  "One indexed": "一方がインデックス付き",
  "Adds tables": "テーブル追加",
  "Moves filters closer to data sources": "フィルタをデータソースに近づける",
  "Changes isolation": "分離レベル変更",
  "Modifies types": "型変更",
  "Table names": "テーブル名",
  "Row counts and distribution": "行数と分布",
  "Data types": "データ型",
  "Access patterns": "アクセスパターン",
  "Table small": "テーブルが小さい",
  "Small fraction of rows, index selective": "少数の行のみ、インデックスが選択性が高い",
  "All columns needed": "すべての列が必要",
  "Index large": "インデックスが大きい",
  "Sorting": "ソート",
  "Table access/bookmark lookups": "テーブルアクセス/ブックマークルックアップ",
  "Joining": "結合",
  "Filtering": "フィルタリング",
  "Nested-loop": "ネステッドループ",
  "Hash": "ハッシュ",
  "Merge": "マージ",
  "Cross": "クロス",
  "Query speed": "クエリ速度",
  "Matching rows / total rows": "一致行数 / 総行数",
  "Columns selected": "選択列数",
  "Accuracy": "精度",
  "All at once": "すべて一度に",
  "Largest on left": "最大を左に",
  "Join new table to existing result": "既存結果に新テーブルを結合",
  "All indexed": "すべてインデックス付き",
  "Execution time": "実行時間",
  "Data distribution and selectivity": "データ分布と選択性",
  "Memory": "メモリ",
  "Network": "ネットワーク",
  "Predicate pushdown": "述語プッシュダウン",
  "Correlated subquery into join": "相関サブクエリを結合に変換",
  "Index selection": "インデックス選択",
  "Join reorder": "結合順序変更",
  "Few rows needed": "少数行が必要",
  "Table small or most rows needed": "テーブルが小さいか大部分の行が必要",
  "Many indexes": "多くのインデックス",
  "GROUP BY": "GROUP BY",
  "Results": "結果",
  "Execution plan": "実行計画",
  "Definitions": "定義",
  "Errors": "エラー",
  "Data partitioning across cores": "データをコア間でパーティショニング",
  "Sequential": "シーケンシャル",
  "Connections": "接続",
  "Caching": "キャッシュ",
  "Rules": "ルール",
  "Dynamic programming for join ordering": "結合順序の動的計画法",
  "Random": "ランダム",
  "Fixed orders": "固定順序",
  "High-cardinality": "高カーディナリティ",
  "Low-cardinality concurrent queries": "低カーディナリティの同時クエリ",
  "Primary keys": "主キー",
  "Foreign keys": "外部キー",
  "Combines views": "ビューを結合",
  "Expands view into query": "ビューをクエリに展開",
  "Materializes": "マテリアライズ",
  "Removes": "削除",
  "Nested-loop variant": "ネステッドループの変種",
  "Filters non-matching probe rows": "一致しないプローブ行をフィルタ",
  "Merge variant": "マージの変種",
  "Cross join": "クロス結合",
  "No index": "インデックスなし",
  "Index with all query columns": "すべてのクエリ列を含むインデックス",
  "Single index": "単一インデックス",
  "Clustered": "クラスタ化",
  "Statistics": "統計",
  "Fixed heuristics": "固定ヒューリスティクス",
  "Cost estimation": "コスト推定",
  "Machine learning": "機械学習",
  "Bandwidth": "帯域幅",
  "Row count per operator": "演算子ごとの行数",
  "Memory": "メモリ",
  "CPU cycles": "CPUサイクル",
  "UNION branches": "UNION分岐",
  "Subquery": "サブクエリ",
  "Index elimination": "インデックス削除",
  "Table elimination": "テーブル削除",
  "Only search": "検索のみ",
  "Search, insert, delete": "検索、挿入、削除",
  "Only insert": "挿入のみ",
  "Only scan": "スキャンのみ",
  "Slower": "遅い",
  "Data only in linked leaf nodes": "データはリンクされたリーフノードにのみ格納",
  "Less data": "データ量が少ない",
  "No deletes": "削除不可",
  "Max key length": "最大キー長",
  "Initial page fill level": "初期ページ充填率",
  "Index levels": "インデックスレベル",
  "Sort order": "ソート順序",
  "Only A": "Aのみ",
  "A, A+B, or A+B+C": "A、A+B、またはA+B+C",
  "Only C": "Cのみ",
  "B,A any order": "B,A 任意の順序",
  "Range queries": "範囲クエリ",
  "Equality only": "等価検索のみ",
  "Sorting": "ソート",
  "Full-text": "全文検索",
  "Query usage": "クエリ用途",
  "Physical data order": "物理データ順序",
  "Max size": "最大サイズ",
  "Index count": "インデックス数",
  "B-tree variant": "B-treeの変種",
  "Bitmaps per value, each bit = row": "値ごとのビットマップ、各ビット＝行",
  "Hash": "ハッシュ",
  "Composite": "複合",
  "Deletes table": "テーブル削除",
  "Recreates reducing fragmentation": "再作成してフラグメンテーション削減",
  "Updates stats": "統計更新",
  "Adds columns": "列追加",
  "last_name": "last_name",
  "city, city+last_name, all three": "city、city+last_name、3列すべて",
  "first_name": "first_name",
  "last_name+first_name": "last_name+first_name",
  "Actual data": "実際のデータ",
  "Keys + row locators": "キー＋行ロケータ",
  "Sorted copy": "ソート済みコピー",
  "FK refs": "外部キー参照",
  "Speed": "速度",
  "Distinct values / total rows": "個別値数 / 総行数",
  "Levels": "レベル数",
  "Size": "サイズ",
  "Manual": "手動",
  "PK and unique constraint": "主キーと一意制約",
  "Temporary": "一時的",
  "Archive": "アーカイブ",
  "Table function": "テーブル関数",
  "Expression result": "式の結果",
  "Stored procedure": "ストアドプロシージャ",
  "View": "ビュー",
  "Reads": "読み取り",
  "Page splits in nearly full pages": "ほぼ満ページでのページ分割",
  "Optimization": "最適化",
  "Rollbacks": "ロールバック",
  "First N rows": "最初のN行",
  "Rows matching WHERE condition": "WHERE条件に一致する行",
  "Indexed columns": "インデックス列",
  "PK values": "主キー値",
  "Hash": "ハッシュ",
  "B+tree on ORDER BY columns": "ORDER BY列のB+tree",
  "Bitmap": "ビットマップ",
  "Full-text": "全文検索",
  "Buffer pool": "バッファプール",
  "Table access": "テーブルアクセス",
  "Joins": "結合",
  "Transactions": "トランザクション",
  "Reads": "読み取り",
  "Writes (DML)": "書き込み（DML）",
  "Planning": "プランニング",
  "Backup": "バックアップ",
  "B-tree variant": "B-treeの変種",
  "Generalized index infrastructure": "汎用インデックスインフラ",
  "Graph index": "グラフインデックス",
  "Geographic only": "地理データのみ",
  "Fan-out 2": "ファンアウト2",
  "All leaves at same depth": "すべてのリーフが同じ深さ",
  "Internal data": "内部データ",
  "Sequential keys": "順次キー",
  "All three": "3つすべて",
  "Two of: C, A, P": "C、A、Pのうち2つ",
  "One": "1つ",
  "C and A": "CとA",
  "Prepare and Execute": "準備と実行",
  "Voting and Commit": "投票とコミット",
  "Lock and Unlock": "ロックとアンロック",
  "Read and Write": "読み取りと書き込み",
  "Immediately consistent": "即時整合性",
  "Replicas converge when updates stop": "更新停止時にレプリカが収束",
  "Never consistent": "整合性なし",
  "Primary only": "プライマリのみ",
  "Duplicates": "重複",
  "Rows across DB instances": "DBインスタンス間で行を分散",
  "Backups": "バックアップ",
  "Compression": "圧縮",
  "Primary done": "プライマリ完了",
  "All replicas confirm": "すべてのレプリカが確認",
  "One replica": "1つのレプリカ",
  "Client confirms": "クライアント確認",
  "Partitioning": "パーティショニング",
  "Network partition with two primaries": "ネットワーク分断で2つのプライマリが発生",
  "Optimization": "最適化",
  "Compression": "圧縮",
  "Timeout": "タイムアウト",
  "Majority agreement": "過半数の同意",
  "Backup": "バックアップ",
  "Optimization": "最適化",
  "Performance": "パフォーマンス",
  "Agreement despite failures": "障害時の合意",
  "Compression": "圧縮",
  "Optimization": "最適化",
  "Eventual": "結果整合性",
  "Causal": "因果整合性",
  "Linearizability": "線形化可能性",
  "Read-your-writes": "読み取り自身書き込み",
  "Easier detection": "検出が容易",
  "Txs at different sites": "異なるサイトのトランザクション",
  "Cannot happen": "発生不可",
  "Read locks": "読み取りロック",
  "After sync": "同期後",
  "Immediately": "即座",
  "After quorum": "クオラム後",
  "Never": "永不応答",
  "Central lookup": "中央検索",
  "Minimal remapping on node change": "ノード変更時の最小再マッピング",
  "Even only": "偶数のみ",
  "No failures": "障害なし",
  "Performance": "パフォーマンス",
  "Causality between events": "イベント間の因果関係",
  "Time sync": "時刻同期",
  "Compression": "圧縮",
  "Single commit": "単一コミット",
  "2PL + 2PC": "2PL + 2PC",
  "No protocol": "プロトコル不要",
  "Three-phase": "3フェーズ",
  "One writer": "ライター1人",
  "Client sees own writes": "クライアントが自身の書き込みを見る",
  "All same data": "すべて同じデータ",
  "Writes invisible": "書き込みが不可視",
  "Primary only": "プライマリのみ",
  "All nodes accept writes": "すべてのノードが書き込み受付",
  "No replication": "レプリケーションなし",
  "Reads only": "読み取りのみ",
  "Availability": "可用性",
  "Read sees latest write": "読み取りが最新書き込みを見る",
  "Throughput": "スループット",
  "Encryption": "暗号化",
  "Local only": "ローカルのみ",
  "Decomposition, transfer, assembly": "分解、転送、組み立て",
  "Security": "セキュリティ",
  "Indexing": "インデックス",
  "Rows": "行",
  "Columns across sites": "サイト間で列を分散",
  "Tables": "テーブル",
  "Backups": "バックアップ",
  "Nothing": "なし",
  "Pre-commit to reduce blocking": "事前コミットでブロッキング削減",
  "Extra logging": "追加ログ",
  "Participants": "参加者",
  "Strict data": "厳密なデータ",
  "Semi-structured varying schemas": "半構造化の多様スキーマ",
  "Relational queries": "リレーショナルクエリ",
  "OLAP": "OLAP",
  "Basic Available, Soft state, Eventual consistency": "Basically Available、Soft state、Eventual consistency",
  "Broad Access, Secure, Encrypted": "Broad Access、Secure、Encrypted",
  "Binary, Standard, Efficient": "Binary、Standard、Efficient",
  "Backup, Archive, Storage": "Backup、Archive、Storage",
  "Complex joins": "複雑な結合",
  "Simple get/put by key": "キーによるシンプルな取得/格納",
  "Full-text": "全文検索",
  "Graph": "グラフ",
  "Batch": "バッチ",
  "Complex relationship traversals": "複雑なリレーションシップ走査",
  "CRUD": "CRUD",
  "Time-series": "時系列",
  "Transactions": "トランザクション",
  "High write throughput, time-series": "高書き込みスループット、時系列",
  "Joins": "結合",
  "ACID": "ACID",
  "NoSQL with SQL": "NoSQL with SQL",
  "SQL+ACID with horizontal scaling": "SQL+ACIDで水平スケーリング",
  "Read scale": "読み取りスケール",
  "No tx": "トランザクションなし",
  "C over A": "CをAより優先",
  "A+P during partitions": "分断時にA+Pを優先",
  "P+C": "P+C",
  "C+A (CA)": "C+A（CA）",
  "Multiple languages": "複数言語",
  "Different DB tech for different uses": "用途ごとに異なるDB技術",
  "Countries": "国",
  "Charsets": "文字セット",
  "TCP": "TCP",
  "Consistency level (ONE, QUORUM, ALL)": "整合性レベル（ONE、QUORUM、ALL）",
  "SQL isolation": "SQL分離レベル",
  "Config": "設定",
  "Eventual": "結果整合性",
  "Causal ops in order": "因果関係のある操作を順序通り",
  "Linearizable": "線形化可能",
  "Read-your-writes": "読み取り自身書き込み",
  "2PL": "2PL",
  "Consensus (Raft/Paxos) with deterministic clocks": "Raft/Paxos合意と確定論的クロック",
  "No support": "サポートなし",
  "Simple locks": "シンプルロック",
  "Joins": "結合",
  "High-volume timestamped data": "高ボリュームのタイムスタンプ付きデータ",
  "Graph": "グラフ",
  "Documents": "ドキュメント",
  "Slower": "遅い",
  "Limited query, no standard language": "クエリが限定的、標準言語なし",
  "Cannot scale": "スケール不可",
  "No indexing": "インデックスなし",
  "Transaction mgmt": "トランザクション管理",
  "Distributed batch processing": "分散バッチ処理",
  "Index creation": "インデックス作成",
  "Schema design": "スキーマ設計",
  "Rows": "行",
  "Column groups (column-oriented)": "カラムグループ（カラム指向）",
  "B-tree": "B-tree",
  "Hash": "ハッシュ",
  "File size": "ファイルサイズ",
  "Sensitivity level": "機密性レベル",
  "Creation date": "作成日",
  "DB type": "DB種別",
  "Network": "ネットワーク",
  "Stored data": "格納データ",
  "Memory": "メモリ",
  "Backup only": "バックアップのみ",
  "Store everything": "すべて保存",
  "Collect only necessary data": "必要なデータのみ収集",
  "Delete daily": "毎日削除",
  "Encrypt all": "すべて暗号化",
  "Admin only": "管理者のみ",
  "Different rows visible per user": "ユーザーごとに異なる行が表示",
  "One per table": "テーブルに1つ",
  "All visible": "すべて表示",
  "Failed queries": "失敗したクエリ",
  "All access and modifications": "すべてのアクセスと変更",
  "Schema only": "スキーマのみ",
  "Logins only": "ログインのみ",
  "Disk": "ディスク",
  "Network transmission": "ネットワーク転送",
  "Memory": "メモリ",
  "Backup": "バックアップ",
  "Keep forever": "永続保存",
  "Delete on request when no legal basis": "法的根拠がない場合、要求に応じて削除",
  "Encrypt only": "暗号化のみ",
  "Anonymize": "匿名化",
  "Alters storage": "ストレージ変更",
  "Obscures results without changing storage": "ストレージを変更せず結果を難読化",
  "Removes data": "データ削除",
  "Encrypts": "暗号化",
  "Individuals": "個人",
  "Roles then assigned to users": "ロールに割り当て、ロールをユーザーに付与",
  "Tables": "テーブル",
  "IPs": "IPアドレス",
  "Speed": "速度",
  "How long to keep data": "データの保持期間",
  "Access": "アクセス",
  "Backup": "バックアップ",
  "Passwords": "パスワード",
  "Parameterized queries": "プリペアドステートメント",
  "Encryption": "暗号化",
  "Hardware": "ハードウェア",
  "Encrypted": "暗号化",
  "Non-sensitive surrogate tokens": "非機密の代理トークン",
  "Random numbers": "乱数",
  "Deleted values": "削除済み値",
  "Admin access": "管理者アクセス",
  "Minimum permissions for task": "タスクに必要な最小権限",
  "Same for all": "全員同じ",
  "DBA only": "DBAのみ",
  "Not needed": "不要",
  "Realistic fake data for testing": "テスト用の現実的な偽データ",
  "Delete all": "すべて削除",
  "Prod encryption": "本番暗号化",
  "Backups": "バックアップ",
  "Database files/pages automatically": "データベースファイル/ページを自動暗号化",
  "Network": "ネットワーク",
  "Application": "アプリケーション",
  "Changed only": "変更分のみ",
  "Entire database": "データベース全体",
  "Metadata": "メタデータ",
  "Log only": "ログのみ",
  "Since last full": "最後のフルバックアップ以降",
  "Since last backup (any)": "最後のバックアップ（いずれか）以降",
  "All from beginning": "最初からすべて",
  "Schema": "スキーマ",
  "Since last full": "最後のフルバックアップ以降",
  "All data": "すべてのデータ",
  "Since last differential": "最後の差分バックアップ以降",
  "Log only": "ログのみ",
  "Max downtime": "最大ダウンタイム",
  "Max data loss in time": "最大データ損失時間",
  "Backup schedule": "バックアップスケジュール",
  "HW replacement": "ハードウェア交換",
  "Max data loss": "最大データ損失",
  "Max restore time": "最大リストア時間",
  "Backup type": "バックアップ種別",
  "Frequency": "頻度",
  "Current time": "現在時刻",
  "Transaction logs for any moment": "任意の時点のトランザクションログ",
  "Backup times": "バックアップ時刻",
  "Random state": "ランダム状態",
  "DB offline": "DBオフライン",
  "DB online and active": "DBオンライン稼働中",
  "Peak hours": "ピーク時",
  "Auto by OS": "OS自動",
  "During operations": "稼働中",
  "DB offline/shutdown": "DBオフライン/シャットダウン",
  "NoSQL only": "NoSQLのみ",
  "Auto hourly": "毎時自動",
  "Storage reduction": "ストレージ削減",
  "PITR between full backups": "フルバックアップ間のポイントインタイムリカバリ",
  "Query speed": "クエリ速度",
  "Schema migration": "スキーマ移行",
  "Log,diff,full": "ログ、差分、フル",
  "Full, latest diff, logs after diff": "フル、最新差分、差分以降のログ",
  "Diff,full,log": "差分、フル、ログ",
  "Full,log,diff": "フル、ログ、差分",
  "Traditional copy": "従来のコピー",
  "Storage instant copy-on-write": "ストレージのインスタントコピーオンライト",
  "Compression": "圧縮",
  "Network": "ネットワーク",
  "Speed": "速度",
  "Backup not corrupted": "バックアップが破損していない",
  "Encryption": "暗号化",
  "Less storage": "ストレージ削減",
  "3 copies, 2 media, 1 offsite": "3コピー、2メディア、1オフサイト",
  "3 full, 2 types, 1 weekly": "3フル、2種別、1週次",
  "3 encryptions, 2 servers": "3暗号化、2サーバー",
  "3 DBs, 2 backups": "3DB、2バックアップ",
  "Physical movement": "物理移動",
  "Auto send logs to standby": "スタンバイへログを自動送信",
  "Manual export": "手動エクスポート",
  "Old deletion": "古いログ削除",
  "Supports PITR": "PITR対応",
  "Auto-truncates log after checkpoint": "チェックポイント後にログを自動切り捨て",
  "Keeps all logs": "すべてのログ保持",
  "Supports shipping": "ログシッピング対応",
  "Read-only queries": "読み取り専用クエリ",
  "Synchronized, can failover": "同期済み、フェイルオーバー可能",
  "Development": "開発用途",
  "Always offline": "常にオフライン",
  "Secure storage": "セキュアストレージ",
  "Testing restores successfully": "リストアテストで正常に復旧できる",
  "Compression": "圧縮",
  "Scheduling": "スケジューリング",
  "Redo only": "REDOのみ",
  "Redo committed + undo uncommitted": "コミット済みをREDO、未コミットをUNDO",
  "Undo only": "UNDOのみ",
  "Full restore": "フルリストア",
  "1 hour": "1時間",
  "15 min or less": "15分以下",
  "5 min": "5分",
  "30 min": "30分",
  "Normal": "正常",
  "Need for verification": "検証の必要性",
  "Inevitable": "不可避",
  "Security": "セキュリティ",
  "Full backup": "フルバックアップ",
  "Auto failover (replication)": "自動フェイルオーバー（レプリケーション）",
  "Incremental": "増分バックアップ",
  "Cold standby": "コールドスタンバイ",
  "Backup only": "バックアップのみ",
  "Roles, procedures, communication": "役割、手順、連絡手段",
  "Hardware only": "ハードウェアのみ",
  "Data only": "データのみ",
  "CPU": "CPU",
  "Daily/weekly/monthly cycles": "日次/週次/月次サイクル",
  "Encryption": "暗号化",
  "Bandwidth": "帯域幅",
  "Full restore": "フルリストア",
  "Transaction log redo/undo": "トランザクションログのREDO/UNDO",
  "Cold backup": "コールドバックアップ",
  "Manual": "手動",
  "Identical": "同じ",
  "Online=active, archived=saved copies": "オンライン＝アクティブ、アーカイブ＝保存済みコピー",
  "Archived larger": "アーカイブの方が大きい",
  "Online optional": "オンラインは任意",
  "Incremental faster": "増分の方が高速",
  "Incremental slower (needs all)": "増分の方が遅い（全増分が必要）",
  "Always faster": "常に高速",
  "Always slower": "常に低速",
  "Archiving": "アーカイブ",
  "Real-time redundancy with failover": "フェイルオーバー付きのリアルタイム冗長化",
  "Optimization": "最適化",
  "Compression": "圧縮",
  "Access": "アクセス",
  "Daily/weekly/monthly backup cycles": "日次/週次/月次バックアップサイクル",
  "Three copies": "3コピー",
  "NoSQL": "NoSQL",
  "Recreate": "再作成",
  "PITR before deletion": "削除前のポイントインタイムリカバリ",
  "Full restore": "フルリストア",
  "No recovery": "リカバリ不可",
  "Software": "ソフトウェア",
  "Time for backups without impact": "影響なしでバックアップ可能な時間",
  "Encryption": "暗号化",
  "Retention": "保持期間"
};

let translated = 0;
let skipped = 0;

questions.forEach(q => {
  const trimmed = q.question.trim();
  if (qMap[trimmed]) {
    q.question = qMap[trimmed];
    translated++;
  } else if (/^[A-Z0-9(=]/.test(trimmed)) {
    console.log(`MISSING Q: ${trimmed.substring(0, 60)}`);
    skipped++;
  }

  if (Array.isArray(q.options)) {
    q.options = q.options.map(opt => {
      if (typeof opt === 'string' && oMap[opt]) {
        return oMap[opt];
      }
      return opt;
    });
  }
});

// Write back as array (the original was array-like object with numeric keys)
const outputPath = path.join(__dirname, 'src/data/db-exam.json');
fs.writeFileSync(outputPath, JSON.stringify(questions, null, 2), 'utf8');

console.log(`\nTranslated: ${translated} questions`);
console.log(`Skipped/missing: ${skipped} questions`);
console.log(`Total: ${questions.length}`);
